### PR TITLE
Introduce service handler for systemd

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
please ignore commit `polipo` as it's a duplicate of the commit in #7 

This PR will introduce a new service model (resource `service::define`) which wants to be initsystem agnostic

@kris-lab do you want to review?

**Comment by ppp0** [comment]
@kris-lab please review - We then need to adapt other modules using custom service init scripts (e.g. bipbip)

**Comment by ppp0** [comment]
retest this please

**Comment by kris-lab** [comment]
Looks good to me. Maybe I would inline spec-templates into spec-manifest as string but I guess it doesn't matter.

**Comment by ppp0** [comment]
@kris-lab I reworked the tests a bit. I learnt a bit about systemd, too. It's not completely obvious migrating from sysV

I added two tests - one for a oneshot-type and the other for a daemon-type service

please review 

Good info:
- https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units
- http://fedoraproject.org/wiki/Packaging%3aSystemd#Fedora_systemd_Services

**Comment by kris-lab** [comment]
What about migration of avoiding the SIGKILL like `--retry TERM/20/TERM/20` when stopping daemon? I see it is possible by some configuration http://www.freedesktop.org/software/systemd/man/systemd.kill.html `SendSIGKILL=false`

Did you have a look into this?

**Comment by ppp0** [comment]
I looked into it, too and I agree `SendSIGKILL=false` sounds like one of the pieces of the puzzle.

But may be it makes also sense to me to group these foreman-debian (Procfile) processes into a master target (cf https://gist.github.com/jonasschneider/4699263). As far as I understand, the master target controls its services and avoids the zombie problem?

Can we test this somewhere else or do you think it should be done here? @njam cc

**Comment by kris-lab** [comment]
Hmm ok. Agree it is not needed here, I meant to find out is it easy doable with systemd.

rest looks good to me!

**Comment by ppp0** [comment]
I think it is doable - may be not with this shutdown choreography (TERM/20/TERM/20) though.

Plus, zombies, it at all, will become children of PID1 (systemd in that case)

**Pull request merged**
