### PR TITLE
Set up CI

### PR DESCRIPTION
**Pull request by ppp0**
Depends on https://github.com/cargomedia/vagrant-boxes/issues/53

### CODE REVIEW

**Comment by ppp0** [comment]
Sorry that is a bit much for a commit.
Like this, rake is able to launch an ubuntu vbox and run specs on it (tested)

For various files, there were changes to be made
e.g.
* modules/puppet/templates/install-apt-sources.sh
* modules/puppet/manifests/common.pp (line 7 !)
* modules/apt - remove as much as possible (e.g. sources) to make it run here first
....

Also, as soon as modules are merged, take a look and adapt `Puppetfile`

@njam do you want to have a look?

**Comment by njam** [comment]
- puppet: PC1 is https://puppetlabs.com/blog/welcome-puppet-collections
 - Adjust comment accordingly
 - Always use PC1?
 - Will this work with our puppet master?

Let's add CI to see the build result!

**Comment by ppp0** [comment]
I agree this mess with repos (PC1, PCn, final releases) is a... well, mess.
May be it would also work to just stick to the last LTS release (in this case vivid?)

Agree to let CI run and see

**Comment by njam** [comment]
Will this PC1 puppet agent work with our puppet master?

**Comment by ppp0** [comment]
>Will this PC1 puppet agent work with our puppet master?

```
puppet --version
3.7.2
```

I believe, yes? Though really not sure if that apt source (pc1) is the good one for us

**Pull request merged**
