### PR TITLE
NVIDIA driver

### PR DESCRIPTION
**Pull request by ppp0**
```
sudo apt-get install nvidia-346
```

### CODE REVIEW

**Comment by ppp0** [comment]
@kris-lab please review

**Comment by kris-lab** [comment]
I am still not sure about final `nvidia` driver. It should work (works for desktop computer) but maybe require some extra configuration for server (current HP Proliant). As experienced it does not work out of the box!

let's investigate and keep it open for now.

**Comment by landswellsong** [comment]
This fixes the GLX and drivers for HP Proliant ML350 (and possibly another ones with 2 graphic cards)
```
#!/bin/sh
# NOTA BENE: this is expected to run AFTER the reboot from apt-get install nvidia-drivers or
# after removing nouveau modules manually

echo "Step 1: Disable modesetting driver, it breaks Xorg -configure"
mv /usr/lib/xorg/modules/drivers/modesetting_drv.so /usr/lib/xorg/modules/drivers/modesetting_drv.so~

echo "Step 2: Auto-configure with X's own means"
X -configure 

echo "Step 3: Move the file back to normal place"
mv -i ~/xorg.conf.new /etc/X11/xorg.conf

echo "Step 4: Restore modesetting driver so it doesn't break the updates"
mv /usr/lib/xorg/modules/drivers/modesetting_drv.so~ /usr/lib/xorg/modules/drivers/modesetting_drv.so

echo "Step 5: Add a custom rule to load NVIDIA's glx xorg module first"
patch -d /etc/X11 <<EOF
--- xorg.conf   2015-10-31 12:46:11.119656923 +0100
+++ xorg.conf-ref       2015-10-31 12:45:26.743234855 +0100
@@ -6,6 +6,8 @@
 EndSection
 
 Section "Files"
+       ModulePath   "/usr/lib/nvidia-346-updates/xorg/"
+       ModulePath   "/usr/lib/nvidia-346/xorg/"
        ModulePath   "/usr/lib/xorg/modules"
        FontPath     "/usr/share/fonts/X11/misc"
        FontPath     "/usr/share/fonts/X11/cyrillic"
EOF
```

**Comment by ppp0** [comment]
Solved in https://github.com/cargomedia/puppet-packages/issues/973

**Comment by ppp0** [comment]
While I see the need to enforce X using NVidia's `libglx.so` (located in one of these custom `ModulePath`s) what happens with upgrade? (e.g. the current nvidia-356). I'd try to rather symlink a non-changing `ModulePath` after installation of new nvidia drivers.. needs verification if it works, though

**Comment by landswellsong** [comment]
@ppp0 ideally the driver will keep either `nvidia-356` or `nvidia-356-updates` directory while updating. As far as I understand (may be wrong a bit), `356` denotes series here rather than version, so it won't become `357` or at least there is a certain version limit after which the newer drivers won't support the hardware. Although the symlink is a good way too.

**Comment by ppp0** [comment]
This seems to be our problem: https://bugs.launchpad.net/ubuntu/+source/nvidia-graphics-drivers-304/+bug/1276123 - Status new, importance undecided and unassigned :smile:

**Comment by landswellsong** [comment]
> 2014-02-04
heh

**Pull request closed without merging**
