### PR TITLE
Add module environment

### PR DESCRIPTION
**Pull request by ppp0**

### CODE REVIEW

**Comment by ppp0** [comment]
@njam please review

**Comment by ppp0** [comment]
This was meant as a test to see if our ci works well. I will now add as as many modules as possible from https://github.com/cargomedia/puppet-packages

**Comment by njam** [comment]
CI is not running?

Shouldn't we only add modules that we need?

**Comment by ppp0** [comment]
all is good. Is this code ok?

**Comment by ppp0** [comment]
I will add modules that will be needed for #4 #5 etc. of course - but that's a few!

**Comment by njam** [comment]
Still no CI status on Github?

**Comment by ppp0** [comment]
retest this please

**Comment by njam** [comment]
Is there a problem with Jenkins not being able to post the build status to Github?
Shouldn't there be a success/failure icon?
Did you check the jenkins logs?

**Comment by ppp0** [comment]
I've restarted jenkins before and then it started to spool `puppet-pacakges-ubuntu-pr` jobs.. but after a failure, it stopped again? Also, the badge is made from builds against `puppet-pacakges-ubuntu`.. I haven't found a way to initiate builds.. not enough rights?

**Comment by njam** [comment]
Ah now there's a checkmark! Huge success!

**Comment by ppp0** [comment]
:tada:

**Pull request merged**
